language:
- python
python:
- '2.7'
env:
  global: 
script: source .travis.sh
after_success:
- set +x
- export GIT_COMMITTER_NAME=$GIT_NAME
- export GIT_COMMITTER_EMAIL=$GIT_EMAIL
- export GIT_AUTHOR_NAME=$GIT_NAME
- export GIT_AUTHOR_EMAIL=$GIT_EMAIL
- echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd
  ~/;            fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  clone --branch gh-pages https://github.com/$TRAVIS_REPO_SLUG doc;  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd
  doc;           fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cp
  -r $TRAVIS_BUILD_DIR/jp ./; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cp
  -r $TRAVIS_BUILD_DIR/en ./; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  status;                  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  add -f jp/*.html en/*.html;                  fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  commit -m "Build documents from $TRAVIS_COMMIT" . ; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  remote -v; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git
  push --quiet https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages; fi
dd:
  secure: DgXdvPskIpatet/MJLj4E2MyO0n+qnpofq191U9j2EmffRLOxlYkUu3PgROoa7Vj7Y3wlKZxRNYaa3WLRcLLQXcBpyWIKg4RllcHkzRuKDb03pqi3vi3oKiNIxQXWzZg0+rETwYX9rLLie92AJ8SOCpWXtN48KELhVZ4u13pwJuB3wihn0wmwEFdIUg3cBL1Aw/oQuxcnfTLdDAjW0dYG+PW5+fAm6EBruLuUlHy0gcQwRwr6LqTfIXotKcAO79W13gHe6kCYOQtEKpjewO/00QghhP34mFFwziSiNkOxzFlPwbinl/0fRSyuIyBzTufrM8dXfK+2Cupk9prFds6EgAQhrTrtVKwxwD2UC4F6xe8wVApRouNMl+g0HaTx9oEuDadDo03EQUDD7xIBW8C1kOO3vYi4q3LodNnYWoz+3jlBL7of6SiQPO+Ygep3T/CENcbfNlWNzR0nfX5S960zh7bs07QApuZwWeRR6EFmVzNHiLfVNlJ1n8RlcXmj4EBZ+Gpu6ug6sEiQWh9I97tq+p278cOL0zE7adUQiYY77AmcyDxUsacjFZgSD1aJ/WZdM8Y8CzaA1abqEPP0N1vraJpzQ4yIDR2dsr4R8MB4pafyhlFy4cfRgbKw0XsL/IMKQdC0GgjsjViMicU5medqI2zdTLEB2Qv5YW3QQi+k9M=
